### ISSUE TITLE
case 8 count syntax wrong

### ISSUE THREAD

**Issue by rutgoff** [binbashar/terraform-aws-cost-budget#4]
in `main.tf` in case 8 the `count` syntax is exactly the same as case 7, breaking case 8.

case 7 (line 375):
```
count = "${var.aws_sns_topic_arn == "" && var.cost_filters_service != "" && var.time_period_end == "" ? 1 : 0}"
```

case 8 (line 436):
```
count = "${var.aws_sns_topic_arn == "" && var.cost_filters_service != "" && var.time_period_end == "" ? 1 : 0}"
```

this should be the following for case 8:
```
count = "${var.aws_sns_topic_arn == "" && var.cost_filters_service == "" && var.time_period_end == "" ? 1 : 0}"
```

notice that `var.cost_filters_service` has `!=` in case 7 and should `==` in case 8

**Comment by exequielrafaela** [comment]
@rutgoff Thanks for reporting this issue we'll take care of it ASAP and let you know when :heavy_check_mark: 

CC: @mpagnucco / @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@rutgoff issued should be solved, please let us know if you try the new `0.0.4` release (https://registry.terraform.io/modules/binbashar/cost-budget/aws/0.0.4) 

CC: @mpagnucco / @diego-ojeda-binbash
