### ISSUE TITLE
amazon changed how budgets access sns

### ISSUE THREAD

**Issue by rutgoff** [binbashar/terraform-aws-cost-budget#5]
This is not your fault, but I think the module can accommodate the issue.
---
# Issue
Amazon wants the access policy for SNS topics to be like so for AWS Budgets to be able to publish:
```
{
  "Sid": "E.g., AWSBudgetsSNSPublishingPermissions",
  "Effect": "Allow",
  "Principal": {
    "Service": "budgets.amazonaws.com"
  },
  "Action": "SNS:Publish",
  "Resource": "your topic ARN"
},
```

ref: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/budgets-sns-policy.html?ref_=pe_26274900_397507290

_However_ the default policy when using Terraform's `aws_sns_topic` resource (and in fact manually creating a topic) is as follows:
```
{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__default_statement_ID",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish",
        "SNS:Receive"
      ],
      "Resource": "your topic ARN",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "111111111111"
        }
      }
    }
  ]
}
```

The issue here is it's the wrong `principal`, and so you get an email alert to your master AWS account login as follows:

> Dear AWS Customer,
>
> 
> You requested that we notify you regarding the status of your <BUDGET_NAME> budget on the following SNS topic: <YOUR_TOPIC_ARN>.
>
> Unfortunately, we are unable to successfully publish to this SNS topic at this time. Please ensure that AWS Budgets has been added to the list of services that are allowed to publish to this SNS topic. You can find additional information on how to add AWS Budgets to your SNS topic permissions here. You can also log in to your AWS Budgets Dashboard to check the status of your budget.
>
> Please note that if you do not adjust your SNS topic permissions, it is likely that budget notifications will not be sent to your SNS topic subscribers.

---
# Possible Solution ?
Looks like you could add an explicit `aws_sns_topic_policy` resource, maybe as follows:
```
resource "aws_sns_topic_policy" "allow_budgets_publish_access" {
  arn = "${aws_sns_topic.sns_alert_topic.arn}"

  policy = "${data.aws_iam_policy_document.sns_topic_default_plus_budgets_policy.json}"
}

data "aws_iam_policy_document" "sns_topic_default_plus_budgets_policy" {
  policy_id = "__default_policy_ID"

  statement {
    actions = [
      "SNS:Publish",
    ]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["budgets.amazonaws.com"]
    }

    resources = [
      "${aws_sns_topic.sns_alert_topic.arn}",
    ]

    sid = "_budgets_service_access_ID"
  }

  statement {
    actions = [
      "SNS:Subscribe",
      "SNS:SetTopicAttributes",
      "SNS:RemovePermission",
      "SNS:Receive",
      "SNS:Publish",
      "SNS:ListSubscriptionsByTopic",
      "SNS:GetTopicAttributes",
      "SNS:DeleteTopic",
      "SNS:AddPermission",
    ]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceOwner"

      values = [
        "${var.account_number}",
      ]
    }

    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = ["*"]
    }

    resources = [
      "${aws_sns_topic.sns_alert_topic.arn}",
    ]

    sid = "__default_statement_ID"
  }
}
```

**EDIT: You'll need the user to supply their account number as an incoming variable though**
**EDIT 2: fixed the syntax in my suggested policy document**

**Comment by exequielrafaela** [comment]
@rutgoff we've faced the same scenario and take almost the same approach setting an `aws_sns_topic_policy` for our SNS Topic orchestrated via `terraform-aws-notify-slack` notification module (https://github.com/binbashar/terraform-aws-notify-slack). We're a going to take your request into consideration and if possible we would try to integrate this setup to be manage by the module itself.   

**NOTE:** In the mean time will be detailing this in the README.md to temporaly help with it. 

```terraform
#============================#
# AWS SNS -> Lambda -> Slack #
#============================#
# Set create_with_kms_key = true
# when providing value of kms_key_arn to create required IAM policy which allows to decrypt using specified KMS key.
module "notify_slack" {
  source = "git::git@github.com:binbashar/terraform-aws-notify-slack.git?ref=v1.13.0"

  create               = true
  create_sns_topic     = true
  create_with_kms_key  = true
  kms_key_arn          = "${aws_kms_key.root-org-key.arn}"
  lambda_function_name = "${var.project}-${var.environment}-notify_slack"
  sns_topic_name       = "${var.sns_topic_name}"
  slack_webhook_url    = "${data.aws_kms_ciphertext.slack_url.ciphertext_blob}"
  slack_channel        = "${var.slack_channel}"
  slack_username       = "${var.slack_username}"
}

resource "aws_sns_topic_policy" "default" {
  arn = "${module.notify_slack.this_slack_topic_arn}"

  policy = "${data.aws_iam_policy_document.sns-topic-policy.json}"
}

data "aws_iam_policy_document" "sns-topic-policy" {
  policy_id = "__default_policy_ID"

  statement {
    actions = [
      "SNS:Publish",
    ]

    effect = "Allow"

    principals {
      type        = "service"
      identifiers = ["budgets.amazon.com"]
    }

    resources = [
      "${module.notify_slack.this_slack_topic_arn}",
    ]

    sid = "_budgets_service_access_ID"
  }

  statement {
    actions = [
      "SNS:Subscribe",
      "SNS:SetTopicAttributes",
      "SNS:RemovePermission",
      "SNS:Receive",
      "SNS:Publish",
      "SNS:ListSubscriptionsByTopic",
      "SNS:GetTopicAttributes",
      "SNS:DeleteTopic",
      "SNS:AddPermission",
    ]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceOwner"

      values = [
        "${var.root_org_account_id}",
      ]
    }

    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = ["*"]
    }

    resources = [
      "${module.notify_slack.this_slack_topic_arn}",
    ]

    sid = "__default_statement_ID"
  }
}
```

CC: @mpagnucco / @diego-ojeda-binbash

**Comment by rutgoff** [comment]
nice! but I got the budgets URL wrong, oops!

it should be `budgets.amazonaws.com`

**Comment by exequielrafaela** [comment]
Yes your're absolutely right w/ `budgets.amazonaws.com` :heavy_check_mark: , my bad :sweat_smile:

**Comment by exequielrafaela** [comment]
Thanks for the heads up here :100: You're absolutely right about `budgets.amazonaws.com` :heavy_check_mark: , my bad :sweat_smile:

**Comment by exequielrafaela** [comment]
@rutgoff issued should be solved now, please let us know if you try the new 0.0.4 release (https://registry.terraform.io/modules/binbashar/cost-budget/aws/0.0.4)

CC: @mpagnucco / @diego-ojeda-binbash
